from generated_code.app.repositories.employee_repository import EmployeeRepository
from generated_code.app.repositories.admin_repository import AdminRepository
from generated_code.app.repositories.report_repository import ReportRepository